version: '3'
services:
  load_balancer:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build:
      context: ./server
    environment:
      - SERVER_ID=1

  server2:
    build:
      context: ./server
    environment:
      - SERVER_ID=2

  server3:
    build:
      context: ./server
    environment:
      - SERVER_ID=3
